import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';

const CLAUDE_SETTINGS_PATH = path.join(os.homedir(), '.claude', 'settings.json');
const FORGE_BIN_DIR = path.join(os.homedir(), '.forge', 'bin');

/**
 * Path where Forge emits the mcp-remote wrapper script.
 */
export const WRAPPER_PATH = path.join(FORGE_BIN_DIR, 'mcp-remote-wrapper');

/**
 * The mcp-remote wrapper script content.
 *
 * Problem it solves: Claude Code spawns MCP servers via `npm exec mcp-remote`,
 * but npm exec does not forward stdin to its child process. When claude exits
 * and closes stdin, `node mcp-remote` never receives EOF and keeps running,
 * accumulating orphaned processes across sessions.
 *
 * Fix: bypass npm exec entirely. Resolve the mcp-remote client.js path once
 * (caching it), then `exec node` directly. With node as the direct child of
 * claude, stdin is properly connected — mcp-remote's `process.stdin.on("end")`
 * handler fires on claude exit, triggering clean self-termination.
 */
const WRAPPER_SCRIPT = `#!/bin/bash
# mcp-remote-wrapper — generated by Forge, do not edit manually.
#
# Exec's mcp-remote directly via node, bypassing npm exec so that stdin EOF
# from claude propagates correctly and mcp-remote self-terminates on session end.
set -euo pipefail

CACHE="\${HOME}/.forge/bin/.mcp-remote-path"

# Resolve and cache the absolute path to mcp-remote/dist/client.js.
# On cache miss (first run or after a version update), npm exec resolves it.
if [ ! -f "\$CACHE" ] || [ ! -f "\$(cat "\$CACHE" 2>/dev/null)" ]; then
  mkdir -p "\$(dirname "\$CACHE")"
  npm exec --yes -- node -e \\
    "process.stdout.write(require.resolve('mcp-remote/dist/client.js'))" \\
    > "\$CACHE" 2>/dev/null || rm -f "\$CACHE"
fi

if [ -f "\$CACHE" ] && [ -f "\$(cat "\$CACHE")" ]; then
  exec node "\$(cat "\$CACHE")" "\$@"
else
  # Fallback: use npx (process may not self-terminate on session end)
  exec npx --yes mcp-remote "\$@"
fi
`;

/**
 * Describes an MCP server to register in ~/.claude/settings.json.
 */
export interface McpServerEntry {
  name: string;
  url: string;
}

/**
 * Emit the mcp-remote wrapper script to ~/.forge/bin/mcp-remote-wrapper.
 * Idempotent — safe to call on every workspace creation.
 * Returns the path to the wrapper.
 */
export async function emitMcpRemoteWrapper(): Promise<string> {
  await fs.mkdir(FORGE_BIN_DIR, { recursive: true });
  await fs.writeFile(WRAPPER_PATH, WRAPPER_SCRIPT, { mode: 0o755, encoding: 'utf-8' });
  return WRAPPER_PATH;
}

/**
 * Merge the given MCP server entries into ~/.claude/settings.json using the
 * managed wrapper script. Preserves all existing settings (permissions, hooks, etc.).
 *
 * Each entry produces a mcpServers record like:
 *   "anvil": { "command": "~/.forge/bin/mcp-remote-wrapper", "args": ["http://...", "--transport", "http"] }
 *
 * Called during workspace creation so every Horus user gets the fix automatically.
 */
export async function updateClaudeMcpServers(servers: McpServerEntry[]): Promise<void> {
  if (servers.length === 0) return;

  await emitMcpRemoteWrapper();

  // Read existing settings, defaulting to empty object on missing/invalid file.
  let settings: Record<string, unknown> = {};
  try {
    const raw = await fs.readFile(CLAUDE_SETTINGS_PATH, 'utf-8');
    settings = JSON.parse(raw);
  } catch {
    // File absent or unparseable — start fresh.
  }

  // Merge: add/overwrite only the servers Forge knows about; leave others intact.
  const mcpServers = (settings.mcpServers as Record<string, unknown>) ?? {};
  for (const { name, url } of servers) {
    mcpServers[name] = {
      command: WRAPPER_PATH,
      args: [url, '--transport', 'http'],
    };
  }
  settings.mcpServers = mcpServers;

  await fs.mkdir(path.dirname(CLAUDE_SETTINGS_PATH), { recursive: true });
  await fs.writeFile(
    CLAUDE_SETTINGS_PATH,
    JSON.stringify(settings, null, 2) + '\n',
    'utf-8',
  );
}
